name: Pull Reqest
on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os: ['windows-latest','ubuntu-latest']
        dotnet-version: ['3.1.201']
        project : ['Json-Rpc']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{matrix.dotnet-version}}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build ${{matrix.project}} --configuration Release --version-suffix ci-${{ github.run_id }}-${{ github.run_number }}
      - name: Test
        run: dotnet test AustinHarris.JsonRpcTestN
      # Publish
      - name: publish nuget version change
        if: ${{matrix.os == 'ubuntu-latest'}}
        run: dotnet nuget push Json-Rpc/bin/Release/*.nupkg  --skip-duplicate --source "https://www.nuget.org" --api-key ${{secrets.NugetKey}} # API key for the NuGet feed
          